### PR TITLE
Revert EditorConfig and clean up #30

### PR DESCRIPTION
**Pull request by abhirooptalasila**
Cleanup

### CODE REVIEW

**Comment by shasheene** [comment]
@abhirooptalasila my preference is a simple git fetch of my branch and `git push -f` to your remote. Skip the GitHub PR request part

**Comment by shasheene** [comment]
So in more detail. On your local git folder:

```
git checkout master
git remote add shasheene https://github.com/shasheene/AutoSub-dev && git fetch shasheene
git reset --hard shasheene/master
git push -f origin master
```

This should produce great looking git history!

**Comment by abhirooptalasila** [comment]
I just wanted to check something manually. 
Is this okay now?

**Comment by shasheene** [comment]
If you open the git history using a tool like `tig` or your preferred tool (on origin/master).

It's in a very ugly state (the multiple layers of merge commits)

I would highly recommend you do a `git reset --hard ac9e68cba6f537642f053f7bcaa2f339855c7329` on your local git folder, then a force push using the git command-line tool (git push -f origin).

This will produce a beautiful git history that I spent a lot of time today creating.

After you do this, I have some great changes I will push :)

**Comment by abhirooptalasila** [comment]
Done.

**Comment by shasheene** [comment]
Beautiful! Thank you so much :D

**Pull request merged**
