### PR TITLE
Fix extraneous colon character in SRT/VTT files, split run-on sentences, 3 digit milliseconds

### LINKED ISSUE #21: Here are the steps to reduce big chunks of text - SRT
Hi,

I did this manually but maybe someone can improve it and write some script for it?:

1. Check text that is longer than 7 words

2. Add a line break to each line longer than 7 words.

3. Get the numbers of lines you got, ie: 
blah blah blah blah blah blah blah
blah blah blah blah blah blah blah
blah blah blah blah blah blah blah
blah blah blah blah blah

There are 4 lines
4. We take the initial and final time

13 <<< SRT Subtitle position
ie: 00:00:25,90 --> 00:00:35,25

5. We surplus them and divide them by the number of lines 
35,25 - 25,90 = 9,35
4 lines of max 7 words each
9,35/4 = 2,33

6. We take 2.33 less 1 for each limit, Ie:

13 <<< SRT Subtitle position
**00:00:25,90** --> 00:00:28,23
blah blah blah blah blah blah blah

14
00:00:28,24 --> 00:00:30,57
blah blah blah blah blah blah blah

15
00:00:30,58 --> 00:00:32,91
blah blah blah blah blah blah blah

16
00:00:32,92 --> **00:00:35,25**
blah blah blah blah blah

14 <<<<  WARNING  >>>> update all the other numbers in this case to 17 (check step 7 below)
blah blah blah blah

7.  We need to update the SRT Subtitle position, in this case we finished at 16, so we need to replace 14 for 17, and do the same for all the other numbers. Note: Update from top to bottom so the counter increments.

That's it.

Anyone? :)

### LINKED ISSUE #31: Malformed SRT/VTT file (extra colon characters)
Thanks for the promising program. I really believe in this work, so I will become an active contributor.

The Python code for subtitles ending with the millisecond section containing zeroes is buggy. I have fixed this (see associated commit), but for the sake of completeness here is a description of the issue.

Here's a excerpt of some generated SRT output that can't load in VLC, mpv and other programs
```
3
00:00:12,95 --> 00:00:14,0:
but you but there

4
00:00:14,60 --> 00:00:15,30
the
```

And the same excerpt from the VTT output:

```
00:00:12.95 --> 00:00:14.0:  align:start position:0%
but you but there
<c> but</c><0:00:13.330000><c> you</c><0:00:13.450000><c> but</c><0:00:13.670000><c> there</c>

00:00:14.60 --> 00:00:15.30  align:start position:0%
the
<c> the</c>
```

The root cause is a broken try/except block in the source code which I have fixed.

I should note that users with sed installed can run commands like `sed -i 's_: -->_ -->_g' filename.srt` to repair the issue, but my attached fix will prevent the issue occurring in the first place.

### PR DESCRIPTION
**Pull request by shasheene**
Fixes #21
Fixes #31 
The 3 digit millisecond commit cherry-picked of public fork. It seemed pretty reasonable to include it here.

See commit messages and referenced issues for more information.

I will cherry-pick the best changes from all the public forks in the coming days and weeks so that AutoSub can become what it should be, and I intend to help you actively maintain and develop this project over the long term.

Thanks!

### CODE REVIEW

**Comment by shasheene** [comment]
Oh, I see you've merged #30 and now this doesn't apply cleanly. I'll fix the conflicts. Give me a moment.

**Comment by shasheene** [comment]
OK I've rebased and now there are no conflicts and this commit is ready to merge.

#30 actually had a lot of unnecessary formatting changes as part of the single commit, which caused conflicts that needed manual resolution with my changes here (and will almost certainly other people's branches that will be applied soon).

**Comment by abhirooptalasila** [comment]
Looks good! 🎉

**Comment by yash-fn** [comment]
Yeah, honestly we should just remove #30 because it will just cause conflicts and doesn't really add anything of value. Also their Dockerfile will completely conflict with my own.

**Comment by shasheene** [comment]
Yeah #30 is a _really_ painful commit that has added so many conflicts. I should have mentioned to hold off merging it. It would have been very easy to apply / recreate the best parts of it as a commit on top after everything else had been merged.

Normally I'd say it's too late now because other work has been merged on top, but I actually agree with the suggestion removing that commit entirely, and re-applying the other changes.

I am happy to do this (and create merge commits using git manually using `git merge --no-ff branch_name`, but it would mean force pushing this repository with the changes.

From their though, the other changes will re-apply much more cleanly. How about I construct such a branch on my fork (https://github.com/shasheene/AutoSub-dev).

Once it's complete (in less than 24 hours), you can fetch and verify those changes (using `git remote add shasheene https://github.com/shasheene/AutoSub-dev && git fetch shasheene` then accept them using `git reset --hard shasheene/master && git push -f origin master`.

Rewriting public history is generally a no-no, but it's definitely the path of least resistance here. And I'll be the one paying the conflict resolution price, so it's no big deal.

Once that's done, I'll immediately have a few future PR's I prepared earlier to apply immediately build upon that cleaner history using the standard PR-based approach.

Sound good?

**Comment by yash-fn** [comment]
I support your proposal!

**Comment by abhirooptalasila** [comment]
Yup sounds doable.

**Pull request merged**
