### PR TITLE
Docker GPU Support and Path Parsing Errors Fix

### PR DESCRIPTION
**Pull request by yash-fn**
Added GPU support for Docker images and a bunch of other related changes to ensure best possible docker experience.

Major Changes:
Base Image is now Ubuntu so we can use NVIDIA's cuda images
Dockerfile was significantly revamped
Dropped unnecessary bit-rate conversion from ffmpeg command
Reordered code to allow instantiating tensor model before failure due to inadequate arguments allowing for useful side effect of faster startup times
Added simple build scripts
There were many errors regarding proper parsing of Paths with metacharacters. They have been fixed where I found them. We should probably stick to using os.path functions instead of manually parsing the strings ourselves.

Also:
Audio directory is directly emptied rather than deleted and recreated. Makes a difference for running docker in Read only mode.
Option to ask for overwriting existing SRT. Default is not to overwrite. Previous default was append, which is not useful.
Dockerfile now just copies training model if available instead of
downloading each time. This enables better developement experience so I
don't have to keep downloading each time I was experimenting with
getting a GPU build. Users can still use newly created convenience script called getmodels.sh to still automatically get what they want.
Other minor improvements like ensuring apt is non-interactive and clears
its cache after installing.
a specific series of copy commands to only copy what is required rather than entire project dir which may have other things users choose to use.

### CODE REVIEW

**Comment by yash-fn** [comment]
I have fixed all the other path parsing errors as they occur in python, but since the ffmpeg command is being run on the shell through python, it must follow shell parsing rules, which is problematic for only one situation: single quotes. Namely the following line from audioprocessing.py:
```bash
ffmpeg -hide_banner -loglevel warning -i '{}' -ac 1 -ar 16000 -vn -f wav '{}'
```
If the path fed to {} contains a ' that will screw the whole thing up. Is there any way someone knows to bypass this?

**Comment by yash-fn** [comment]
God this is probably the ugliest thing I've seen, but it appears to work:
```bash
command = "ffmpeg -hide_banner -loglevel warning -i '{}' -ac 1 -ar 16000 -vn -f wav '{}'".format(input_file.replace("'","'"'"'"'"'"'"'"), audio_file_name.replace("'","'"'"'"'"'"'"'"))
```

**Comment by yash-fn** [comment]
Parsing paths in bash is such a complete pain. I wish they made it more intuitive.

**Comment by yash-fn** [comment]
Okay, I'm done with all my edits. It's ready to merge. It now supports any conceivable pathname you can throw it at it and has full GPU support via docker.

**Comment by shasheene** [comment]
Hi @yash-fn,

Great work. I have examined  your changes and the Docker stuff generally looks good for @abhirooptalasila to merge.

There are two commits that would cleanly squash into "Added convenience scripts for building CPU vs GPU images" (the commits are "Edited build scripts to work from their current location" and "build scripts needed quotes").

With the ffmpeg call, there's actually a simpler and smarter way do escaping. Before your changes, the command looks like this:
```
command = "ffmpeg -hide_banner -loglevel warning -i {} -b:a 192k -ac 1 -ar 16000 -vn {}".format(
        input_file, audio_file_name.replace(" ", "\ "))
    try:
        ret = subprocess.call(command, shell=True)
```
I should note the subprocess.call is part of the [old](https://docs.python.org/3/library/subprocess.html) API, but more importantly, the shell=True is not required here. It causes the filenames to be interpreted by the shell (and therefore need escaping), but it's something that can be avoided.

Instead, providing the command as a list bypasses the need to do the character escaping For example:
```
command = ["ffmpeg", "-hide_banner", "-loglevel" , "warning", "-i", input_file, "-b:a", "192k", "-ac", "1", "-ar", "16000" , "-vn", output_file]
ret = subprocess.run(command).returncode
```
This correctly handles any character you can throw at it (even a filename containing many special characters like `!@#$%^'`).

I am happy to take all the relevant commits from your branch and replace the escaping stuff with a improved solution.

**Comment by shasheene** [comment]
Oops, I pressed Enter too early. I was about to say: @abhirooptalasila, I am happy to take @yash-fn's branch merged with the improvements that I described above.

Then I will evaluate and apply the PR from #30 (by @SethFalco), followed by adapting and merging the large number of changes @qlchan24 pushed publicly over the last two months (which overlaps/conflicts with some changes I have pushed in my most recent pull request).

I have the time and motivation to immediately start improving the project by integrating all public forks, fixing the bugs and adding some new features.

**Comment by yash-fn** [comment]
Hi shasheene! Thanks for the feedback! And I like your subprocess code better than mine! When I next get the time (hopefully this weekend) I will work to incorporate those changes. Alternatively, if you have the time before me as you suggested, I have added you as a collaborator to my branch so you can just directly modify it as you wish. I also feel this project has potential to grow into something much better!

**Comment by abhirooptalasila** [comment]
Hi 
I don't have access to a GPU so I'm trusting you to have done all the necessary checks. 
@shasheene should I merge this PR and then you can work on the other part?

**Comment by shasheene** [comment]
@abhirooptalasila,

@yash-fn has just given me collaborator access to his repository.

I have a lot of time right at the moment so I am happy to do the necessary squash, rebase and modifications on this Pull Request to improve it. I am happy to test the GPU parts on this PR after my changes before pushing.

If you're happy with #32 (after the README update request) then please merge it.

I am intending on pushing several Pull Requests over the next few days.

**Comment by yash-fn** [comment]
Yes. GPU is now fully compatible because the base image switch to NVIDIA's official CUDA image. We can now, moving forward, avoid reinventing the wheel on GPU support and essentially just trust that the company itself will support and thoroughly test their own hardware and the images should in theory "just work". And I can at least confirm that it works as expected on my own 1070 TI GPU.

**Comment by abhirooptalasila** [comment]
That's good. @shasheene please rebase @yash-fn 's work and then I'll merge it. 
Thanks!

**Comment by yash-fn** [comment]
hey @abhirooptalasila, please consider adding a dev branch where we can just screw around trying to get a working build and then a master branch that lags until things have tested and can then push it onto a published release. Also, we should consider publishing the docker image on docker hub for others to just directly download and use from docker cli utility.

**Comment by shasheene** [comment]
Having a dev branch is definitely one path, and has been used successfully before.

But another approach is to tag an official/stable release, then have master be the unstable/"dev" branch.

The build instructions would then simply contain eg,
```
git clone https://github.com/abhirooptalasila/AutoSub/pull/29
# Checkout most recent tag
git checkout $(git describe --tags --abbrev=0)
# Rest of instructions
```

The advantage of using tags extensively is users of the tool can jump to a number of known stable configurations instantly.

Currently AutoSub has only 1 tag (v1.0.0) from way back in September 2019.

Better versioning means if v1.1.0 was the latest version, a new "v1.2.0" could be released, but also a v1.1.1 hot fix to fix some minor bugs and users can easily choose the most suitable library for their needs based on the Changelog/release notes.

@abhirooptalasila  thoughts?

**Comment by yash-fn** [comment]
Works for me! And actually seems cleaner too. Never really used tags so don't have much experience with them, but sounds great.

**Comment by shasheene** [comment]
They're simply a named immutable name of a commit. And a branch is a mutable name of a commit

Kind of like a branch, but you can't modify them.

 We'll you're free to delete the tag and create a new one, but you don't build upon a tag. You would create a temporary branch based on the `git checkout -b test_branch v1.0.0`, then add some commits and maybe late create a new tag `git tag v1.0.1`.

You can play with them on your local environment. The syntax for pushing a tag to a remote (like GitHub) is something I tend to lookup everytime though.

**Comment by abhirooptalasila** [comment]
Yup, tags are a much easier and cleaner way to about it. 
I think after these changes are merged, I'll test everything and then tag it as 2.0?
I'll add the image to Docker hub soon. Thanks for the suggestion.

**Comment by yash-fn** [comment]
Yeah for sure I will check them out.

**Comment by shasheene** [comment]
> I think after these changes are merged, I'll test everything and then tag it as 2.0?

Personally I generally follow [Semantic Versioning](https://semver.org/):
```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

Notably the Linux kernel doesn't follow this because they never break the API. They only deprecate features that are later removed.

So if the AutoSub API is its command-line interface, then yes technically there is a "breaking" change the upcoming `--vtt` to `--format` of #33 and so it should be v2.0.0 under Semantic Versioning.

But I think your project will become the world's defacto subtitling tool over the next 20 years. Like eventually it will generate perfect subtitles for all human speech in any language. Given this, I don't think jumping to a v2.0.0 version so soon is a good idea. Well unless you want to eventually reach v73.0.0, like Firefox and Google Chrome admittedly have done.

Personally, I think all the changes being done constitute v1.1.0. And then we can do v1.2.0 (by the way, v1.9.0 can be followed by v1.10.0). The key is when v2.0.0 or v3.0.0 of AutoSub will be released, that should be a massive event that gets a huge amount of publicity on news websites and web forums.

Just some thoughts. It's @abhirooptalasila choice what the next version number will be.

**Comment by abhirooptalasila** [comment]
Haha. Yeah, I agree a lot has been changed since the initial release, but we can probably hold off the major version change.
I also have a couple of good changes that I want to implement. Will do it soon.

**Comment by shasheene** [comment]
Ok @abhirooptalasila, I have painstakingly fixed the last few merges to remove all the conflicts introduced by the early merging of #30. You can find my branch here: https://github.com/shasheene/AutoSub-dev

Please `git fetch` my changes and force push it to your branch. This will also close @yash-fn  Pull Request.

I have improved some commit messages and made a few other minor changes (fixing tabs vs spaces in README file etc). I also removed the `--overwrite` argument because the `--format` approach that will be introduced with #33 will mean overwriting is the default behavior.

I will do the path parsing fix on top, as it requires more changes that the exiting commit.

This was a heck of a lot of effort, and there's still a lot more commits from other forks that I want to merge. **I will create several more PR's in the next few hours with some great new features.** Hopefully my relatively large changes to the Python code doesn't conflict with any changes @yash-fn will add. I am trying to avoid wasting more time resolving git conflicts.

**Pull request closed without merging**
