### PR TITLE
Add normalization to sox call.

### PR DESCRIPTION
**Pull request by xfim**
I believe it can improve the capacity to recognize patterns, from my rudimentary tests. But I am curious about what you think.

Another, more complex option, would be to do it to each of the small chunks of audio, one by one. In that case, I have not been able to find a suitable function on pyAudioAnalysis. But I am sure there must be one way to do it.

Thank you very much for the tool.

### CODE REVIEW

**Comment by abhirooptalasila** [comment]
Hi
Sox has a [default norm](https://github.com/rabitt/pysox/blob/3dfa01596a86fdec037325422ea9b5bf481f619c/sox/transform.py#L2435) value of -3.0. I think the value you've provided in the CLI argument works better for your use case. 
How big of a difference is visible in your generated subtitles?

**Comment by xfim** [comment]
Honestly, I have tried now and explicitly using -3.0 gives slightly (very slightly) better values than my proposal of -0.1. But I have to admit that I have used it / adapted it not in the context of a movie with arranged audio, but using more domestic / low quality videos with poorer audios. 

Comparing using -0.1 and nothing gives better results to the default (nothing), but not so well as -3.0.


So I leave it to you what to do with it. I am far a way from being an expert.

**Comment by abhirooptalasila** [comment]
I think -3.0 works best for a variety of use-cases. Thank you!

**Comment by xfim** [comment]
Thank you.

**Pull request merged**
